import pandas as pd
import streamlit as st

st.markdown(
    """
    <style>
        /* Make the main content area wider */
        .block-container {
            max-width: 70%;
            padding-top: 2rem;
        }

        /* Make the Sidebar Logo larger */
        [data-testid="stSidebarHeader"] img {
            max-height: 100px; /* Adjust height as needed */
            width: auto;
        }
    </style>
    """,
    unsafe_allow_html=True
)

st.title("History of the association")

history_text = """On October 27, 1915, fourteen librarians and library supporters met in the University of South Carolina Library in response to an invitation from Robert M. Kennedy published the previous day in The State newspaper. Those present voted unanimously to establish the South Carolina Library Association, the purposes of which would be "to arouse and stimulate an interest in the development of libraries, to be a medium of information in (that) regard..., and to bring into touch her library force that they may gather additional strength and inspiration for the work."""
st.markdown(history_text)

st.link_button(
    "A South Carolina Library Association: Advocate for Libraries",
    "http://www.libsci.sc.edu/histories/sclahistory/scla.htm",
    help="A history of the association from 1915-1990 by Roger Hux, published in 1990",
)

dates_data_table = {
    "Year": [
        1915,
        1916,
        1917,
        1918,
        1919,
        1920,
        1921,
        1922,
        1923,
        1924,
        1925,
        1926,
        1927,
        1928,
        1929,
        1930,
        1931,
        1932,
        1933,
        1934,
        1935,
        1936,
        1937,
        1938,
        1939,
        1940,
        1941,
        1942,
        1943,
        1944,
        1945,
        1946,
        1947,
        1948,
        1949,
        1950,
        1951,
        1952,
        1953,
        1954,
        1955,
        1956,
        1957,
        1958,
        1959,
        1960,
        1961,
        1962,
        1963,
        1964,
        1965,
        1967,
        1969,
        1971,
        1972,
        1973,
        1974,
        1975,
        1976,
        1977,
        1978,
        1979,
        1980,
        1981,
        1982,
        1983,
        1984,
        1985,
        1986,
        1987,
        1988,
        1989,
        1990,
        1991,
        1992,
        1993,
        1994,
        1995,
        1996,
        1997,
        1998,
        1999,
        2000,
        2001,
        2002,
        2003,
        2004,
        2005,
        2006,
        2007,
        2008,
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        2018,
        2019,
        2020,
        2021,
    ],
    "President": [
        "R. M. Kennedy",
        "R. M. Kennedy",
        "R. M. Kennedy",
        "R. M. Kennedy",
        "R. M. Kennedy",
        "R. M. Kennedy",
        "R. M. Kennedy",
        "Louise McMaster",
        "Louise McMaster",
        "Louise McMaster",
        "John Peyre Thomas, Jr.",
        "Charlotte Templeton",
        "Charlotte Templeton",
        "Charlotte Templeton",
        "Mrs. Henry Lee Buck",
        "R. Beverly Herbert",
        "Ellen Perry",
        "Lucy Hampton Bostick",
        "Ora A. Willis",
        "Parmelee Cheves",
        "Fanny T. Taber",
        "Cornelia Ayer Graham",
        "Willard Jones",
        "Fant H. Thornley",
        "Fant H. Thornley",
        "Annie Porter",
        "Maude Query Kelsey",
        "Alfred Rawlinson",
        "J. Isaac Copeland",
        "Lewis C. Branscomb",
        "Helen Hagan",
        "Mary Cox",
        "Frances Lander Spain",
        "Emily Sanders",
        "J. Mitchell Reames",
        "Naomi Derrick",
        "Nancy C. Blair",
        "Herbert Hucks, Jr.",
        "Desmond Koster",
        "Lois Barbare",
        "Nancy Burge",
        "Robert C. Tucker",
        "Charles E. Stow",
        "Madeline Mosimann",
        "J. W. Gordon Gourlay",
        "Marguerite G. Thompson",
        "Nancy Jane Day",
        "Jessie Gilchrist Ham",
        "Elizabeth B. Foran",
        "Betty Martin",
        "Susie Norwood McKeown",
        "Josephine Crouch",
        "Carol S. Scott",
        "J. Mitchell Reames",
        "J. Frank Nolen",
        "J. Frank Nolen",
        "Estellene P. Walker",
        "Estellene P. Walker",
        "Kenneth E. Toombs",
        "Margaret W. Ehrhardt",
        "Lennart Pearson",
        "Martin Pautz",
        "John H. Landrum",
        "William Summers",
        "Gerda Belknap",
        "Paul Dove",
        "Drucilla Reeves",
        "Carl Stone",
        "Susan Hollifield",
        "Barbara Williams Jenkins",
        "Suzanne Krebsbach",
        "Betty Callaham",
        "Joseph F. Boykin, Jr.",
        "Sarah McMaster",
        "David Cohen",
        "Claude Blakely",
        "Deborah Stone (Coleman)",
        "Deborah Stone (Coleman)",
        "Felita Suzette Green",
        "Tom Sutherland",
        "Faith Line",
        "Betsey Carter",
        "Norman Belk",
        "Glynda Christian",
        "Jeanette Bergeron",
        "Thomas Gilson",
        "Marilyn Tsirigotis",
        "Elizabeth Shuping",
        "Joyce Durant",
        "Quincy Pugh",
        "Curtis Rogers",
        "Libby Young",
        "Rayburne Turner",
        "Adam Haigh",
        "Yvonne Davis",
        "Jonathan Newton",
        "Ed Rock",
        "Crystal Johnson",
        "John Kennerly",
        "Amber Conger",
        "Jimmy Epling",
        "Amanda Stone",
        "Nathan Flowers",
        "Megan Palmer",
    ],
    "Location": [
        "Columbia",
        "",
        "Columbia",
        "",
        "",
        "",
        "Darlington",
        "",
        "",
        "Greenville",
        "Charleston",
        "",
        "Columbia",
        "Florence",
        "Columbia",
        "Greenville",
        "Columbia",
        "Columbia",
        "Charleston",
        "Summerville",
        "Rock Hill",
        "Beaufort",
        "Sumter",
        "Charleston",
        "Columbia",
        "Greenville",
        "Columbia",
        "Columbia",
        "Columbia",
        "Columbia",
        "Columbia",
        "Asheville, NC",
        "Charleston",
        "Myrtle Beach",
        "Greenville",
        "Atlanta, GA",
        "Clemson",
        "Myrtle Beach",
        "Columbia",
        "Charleston",
        "Columbia",
        "Clemson",
        "Charleston",
        "Columbia",
        "Clemson",
        "Columbia",
        "Charleston",
        "Greenville",
        "Columbia",
        "Charleston",
        "Greenville",
        "Myrtle Beach",
        "Greenville",
        "Columbia",
        "Columbia",
        "Myrtle Beach",
        "Columbia",
        "Charleston",
        "Columbia",
        "Myrtle Beach",
        "Columbia",
        "Charleston",
        "Columbia",
        "Charlotte, NC",
        "Columbia",
        "Greenville",
        "Columbia",
        "Charleston",
        "Columbia",
        "Greenville",
        "Myrtle Beach",
        "Hilton Head",
        "Columbia",
        "Greenville",
        "Columbia",
        "Charleston",
        "Myrtle Beach",
        "Columbia",
        "Greenville",
        "Myrtle Beach",
        "Columbia",
        "Hilton Head",
        "Columbia",
        "Myrtle Beach",
        "Charleston",
        "Columbia",
        "Greenville",
        "Columbia",
        "Hilton Head",
        "Columbia",
        "Greenville",
        "Columbia",
        "Myrtle Beach",
        "North Charleston",
        "Columbia",
        "Greenville",
        "Columbia",
        "Columbia",
        "Columbia",
        "Columbia",
        "Greenville",
        "Columbia",
        "Columbia",
        "Virtual",
    ],
    "Dates": [
        "Oct. 27",
        "",
        "Mar. 14-15",
        "",
        "",
        "",
        "Nov. 17-18",
        "",
        "",
        "Mar. 27-28",
        "Apr. 14-15",
        "",
        "Feb. 22-23",
        "Apr. 2-3",
        "Apr. 4-5",
        "Apr. 11-12",
        "Apr. 9-10",
        "May 11-12",
        "May 3-4",
        "Apr. 20-21",
        "Oct. 4-5",
        "May 29-30",
        "May 7-8",
        "Mar. 18-19",
        "Feb. 10-11",
        "Apr. 26-27",
        "Nov. 7-8",
        "Nov. 6-7",
        "Dec. 1-2",
        "Nov. 24-25",
        "Nov. 9-10",
        "Oct. 25",
        "Oct. 1-Nov.1",
        "Sept. 24-25",
        "Sept 30-Oct.1",
        "Oct. 14",
        "May 4-5",
        "Apr. 18-19",
        "Oct. 30-31",
        "Oct. 29-30",
        "Oct. 28-29",
        "Oct. 26-27",
        "Oct. 25-26",
        "Oct. 31-Nov.1",
        "Oct. 30-31",
        "Oct. 28-29",
        "Nov. 3-4",
        "Oct. 26-27",
        "Nov. 1-2",
        "Oct. 16-17",
        "Oct. 29-30",
        "Oct. 5-7",
        "Oct. 9-11",
        "Oct. 7-9",
        "Oct. 13",
        "Oct. 11-13",
        "Oct. 4",
        "Oct. 9-11",
        "Oct. 21-23",
        "Oct. 13-15",
        "Oct. 12-14",
        "Oct. 11-13",
        "Oct. 9-11",
        "Oct. 7-9",
        "Oct. 7-9",
        "Oct. 13-15",
        "Sept. 13-15",
        "Oct. 10-12",
        "Oct. 30- Nov.1",
        "Oct. 14-6",
        "Nov. 9-11",
        "Nov. 15-17",
        "Oct. 17-19",
        "Nov. 5-8",
        "Oct 21-23",
        "Dec. 8-10",
        "Feb. 22-24, 1995",
        "Dec. 6-8, 1995",
        "Oct. 30-Nov. 1",
        "Nov. 12-14",
        "Oct. 21-23",
        "Dec. 1-4",
        "Oct. 28",
        "Mar. 15-17",
        "Oct. 24-26",
        "Oct. 22-24",
        "Oct. 27-29",
        "Oct. 26-28",
        "Nov. 29 - Dec. 1",
        "Oct. 31 - Nov. 2",
        "Oct. 22-24",
        "Oct. 28-30",
        "Oct. 20-22",
        "Oct. 19-21",
        "Oct. 24-26",
        "Nov. 13-15",
        "Oct. 22-24",
        "Oct. 21-23",
        "Nov. 9-11",
        "Oct. 11-13",
        "Oct. 31 - Nov. 2",
        "Oct. 9-11",
        "Oct. 6-9",
        "Oct. 5-7",
    ],
}

friend_award_winners_table = [
    (1976, "Jean Galloway Bissel", "Columbia"),
    (1977, "Arthur McGill", "Greenville"),
    (1978, "Lillian Hart", "Clinton"),
    (1979, "Carlisle Bean", "Spartanburg"),
    (1980, "Jean E. Crouch", "Saluda"),
    (1981, "B. O. Thomason, Jr.", "Greenville"),
    (1982, "Harriet Keyserling", "Beaufort County"),
    (1982, "Thomas Smith", "Florence County"),
    (1983, "Sarah Miles Norton", "Oconee County"),
    (1984, "Judy Pendarvis", "Edgefield County"),
    (1985, 'C. P. "Margie" Porterfield', "Lexington County"),
    (1986, "Bright Parker", "Gaffney"),
    (1987, "Francie Dunlap", "Florence"),
    (1988, "King Dixon", "Laurens County"),
    (1989, "Elma Sanders Rogers", "Colleton County"),
    (1990, "M. Penelope Davis", "Charleston"),
    (1991, "Dr. Rhonda C. Stanton", "Francis Marion College"),
    (1993, "Friends of Richland County Library", None),
    (1994, "Chapin Foundation of Myrtle Beach", None),
    (1996, "Virginia M. Delaney", None),
    (1996, "D. Lindsay Pettus", None),
    (1997, "Mozell T. Robinson", "Chester County"),
    (1998, "Harriet Woodham", "Richland County"),
    (1999, "Barbara Roberts", "Friends of McCormick County Library"),
    (1999, "Lou Roberts", "Friends of McCormick County Library"),
    (
        2002,
        "Dr. Randy L. Akers",
        "Executive Director of the South Carolina Humanities Council",
    ),
    (2003, "David R. Dickerson", "Fort Jackson"),
    (2004, "Senator Gerald Malloy", None),
    (2005, "Tom Fletcher", "Fairfield County"),
    (2008, "Drs. Bruce and Lee Foundation of Florence", None),
    (2011, "Clara Mae Neuman", "Charleston County Public Library"),
    (2018, "Friends of the Hilton Head Library", None),
    (
        2024,
        "Friends of the Green Sea Floyds Library",
        "Horry County Memorial Library - Green Sea Floyds Library",
    ),
]

outstanding_award_winners_table = [
    (1986, "Marvin Stewart", "Charleston County"),
    (1987, "Dennis Bruce", "Spartanburg County"),
    (1988, "Leslie Abrams", "Clemson University"),
    (1989, "Virginia Foley Nilles", "Georgetown County"),
    (1990, "Louise McAuley", "Marion County"),
    (1991, "David Warren", "Richland County"),
    (1992, "Sherman Pyatt", "The Citadel"),
    (1993, "Faith Line", "Sumter County"),
    (1994, "Norman Belk", "Greenville County"),
    (1995, "John Landrum", "South Carolina State Library"),
    (1996, "Katina Strauch", "College of Charleston"),
    (1997, "Lennart Pearson", "Presbyterian College"),
    (1998, "Helen Ann Rawlinson", "Richland County"),
    (2002, "Mary Bull", "South Carolina State Library"),
    (2003, "Marguerite D. Keenan", "Pickens County"),
    (2004, "Dennis Adams", "Beaufort County"),
    (2005, "Libby Law", "South Carolina State Library"),
    (2006, "Guynell Williams", "South Carolina State Library"),
    (2007, "Ray Turner", "Charleston County"),
    (2009, "Ray McBride", "Florence County"),
    (2010, "Pamela Davenport", "South Carolina State Library"),
    (2011, "Deborah Rollerson Harris", "Charleston County"),
    (2018, "Amber Conger", "Kershaw County"),
    (2019, "Annie Sutton", "Anderson County"),
    (
        2024,
        "Marilynn Lance-Robb",
        "Branch Manager, Georgetown County Library - Carvers Bay Library",
    ),
]

outstanding_professional_award_table = [
    (1986, "Virginia Warr", "Hartsville"),
    (1987, "Angela Bardin", "South Carolina Supreme Court"),
    (1989, "Cynthia Yarborough", "Presbyterian College"),
    (1990, "Denise Jacobs", "Monarch Elementary, Union"),
    (1992, "Frankie Ashburn", "North Carolina Center for the Book"),
    (1997, "Judith Jordan", "Greenville County Public Library"),
    (1998, "Cary Jones", None),
    (2001, "Laura Holden", "Anderson County Library"),
    (2003, "Maria Jones", "Beaufort County Library"),
    (2004, "Derek Wilmott", "University of South Carolina – Columbia"),
    (2005, "Stacy Winchester", "Greenville County Public Library"),
    (2018, "Danielle Thornton", "Greenville County"),
    (2019, "Emily Jones", "MUSC 2024"),
    (
        2024,
        "McKenzie Lemhouse",
        "Assistant Librarian, Instruction & Outreach, University of South Carolina - Lancaster",
    ),
]

outstanding_support_table = [
    (1997, "Betty Cook", "Clemson University Library"),
    (1998, "Rayburne Turner", "Charleston County Library"),
    (1999, "Barbara H. Gillard", "South Carolina State Library"),
    (2001, "Roberta White", "Spartanburg County Library"),
    (2003, "Lorraine Catoe", "Richland County Library"),
    (2008, "Faith Keller", "South Carolina State Library"),
    (2011, "Janell Eades", "South Carolina State Library"),
    (2016, "Laura Baines", "Furman University"),
    (2018, "Sarah Ward", "TriCounty Technical College"),
    (2019, "LaKisha Perrin", "Richland Library"),
    (2024, "Carl Redd", "Archives Specialist, Clemson University"),
]

intellectual_freedom_table = [
    (1983, "Pat Scales", None),
    (1985, "Daniel Barron", None),
    (1985, "Melinda Hare", None),
    (1986, "Betty E. Callaham", "South Carolina State Library"),
    (1988, "Eva Roussos", None),
    (1989, "Judith Fitzgerald", None),
    (1993, "Patricia Lightweiss", None),
    (1995, "Robert New", None),
    (1998, "Phil Ritter", "Greenville County Library"),
    (1999, "John Monk", None),
    (2001, "Ida Thompson", None),
    (2001, "Betty Garrison", None),
    (2002, "Carl Stone", "Anderson County Library"),
    (2003, "Pat Scales", None),
    (2005, "J. Rhett Jackson", None),
    (2007, "Michael Giller", None),
    (2011, "Emily Woody", None),
    (2013, "Anne C. Lemieux", None),
    (2014, "Marlon Kimpson", None),
    (2019, "Jonathan Newton", None),
    (
        2024,
        "Tamara Cox",
        "Media Specialist Teacher, Wren High School (Anderson School District 1)",
    ),
]

grassroots_table = [
    (1987, "Elizabeth Bonniwell"),
    (1988, "Denise Jacobs"),
    (1989, "Stephen Escar Smith"),
    (1990, "Teresa Price Lanford"),
    (1991, "Gayle Holmes"),
    (1992, "David Vassar"),
    (1993, "Wang Ying"),
    (1994, "Lynne Douglas-Simmons"),
]

distinguished_table = [
    (1983, "Estellene P. Walker", "South Carolina State Library"),
    (1983, "J. Mitchell Reames", "Francis Marion College"),
    (1989, "Margaret Haynes", "Laurens County"),
    (1989, "Valerie Howard Stanley", "South Carolina State University"),
    (2003, "Margie E. Herron", "South Carolina State Library"),
    (2018, "Ray McBride", "Beaufort County"),
    (2019, "Faith Line", "Anderson County"),
    (
        2024,
        "Cathi Mack, Assistant to the Dean, Coordinator of Technical Services, Instructor",
        "South Carolina State University",
    ),
]

gavel_table = [
    (1989, "Betty E. Callaham", "South Carolina State Library"),
    (1992, "David Cohen", None),
]

student_table = [
    (2019, "Emilie J. Hancock", None),
    (
        2024,
        "Ramon Maclin, Adult Services Librarian",
        "Charleston County Public Library - Keith Summey North Charleston Library",
    ),
]

scholarship_table = [
    (2002, "Pamela D. Williams"),
    (2007, "Annie Young Patrick"),
    (2008, "Paula Alvarez"),
    (2008, "Joi Gilliam"),
    (2008, "K'Lani Green"),
    (2009, "Elizabeth Harris"),
    (2010, "Melanie Slan"),
    (2010, "Parri Wright"),
    (2011, "Rebecca Kilby"),
    (2011, "Alex McAllister"),
    (2011, "Antonio Peterson"),
    (2012, "Wanda Preister"),
    (2012, "Carolina Sanders"),
    (2012, "Tammie Wells"),
    (2013, 'Shamora "Marleigh" Chiles'),
    (2013, "Wanda Priester"),
    (2014, "Bettina Thomas"),
    (2015, "Jasmine Williams"),
    (2016, "Phoebe Blalock"),
    (2016, "Tiara Cureton"),
]

dates_data_df = pd.DataFrame(dates_data_table)
friend_award_winners_df = pd.DataFrame(
    friend_award_winners_table, columns=["Year", "Winner", "Location"]
)
outstanding_award_winners_df = pd.DataFrame(
    outstanding_award_winners_table, columns=["Year", "Winner", "Location"]
)
outstanding_professional_winners_df = pd.DataFrame(
    outstanding_professional_award_table, columns=["Year", "Winner", "Location"]
)
outstanding_support_df = pd.DataFrame(
    outstanding_support_table, columns=["Year", "Winner", "Location"]
)
intellectual_freedom_df = pd.DataFrame(
    intellectual_freedom_table, columns=["Year", "Winner", "Location"]
)
grassroots_df = pd.DataFrame(grassroots_table, columns=["Year", "Winner"])
distinguished_df = pd.DataFrame(
    distinguished_table, columns=["Year", "Winner", "Location"]
)
gavel_df = pd.DataFrame(gavel_table, columns=["Year", "Winner", "Location"])
innovation_df = pd.DataFrame([(2018, "Richland Library Social Awareness Taskforce")])
student_df = pd.DataFrame(student_table, columns=["Year", "Winner", "Location"])
scholarship_df = pd.DataFrame(scholarship_table, columns=["Year", "Recipient"])

with st.expander("Past Conference Dates"):
    st.table(dates_data_df, border="horizontal")

with st.expander("Friend of Libraries Award Winners"):
    st.table(friend_award_winners_df, border="horizontal")

with st.expander("Outstanding Librarian Award Winners"):
    st.table(outstanding_award_winners_df, border="horizontal")

with st.expander("Outstanding New Professional Award Winners"):
    st.table(outstanding_professional_winners_df, border="horizontal")

with st.expander("Outstanding Library Support Staff Award Winners"):
    st.table(outstanding_support_df, border="horizontal")

with st.expander("Grassroots Award Winners"):
    st.table(grassroots_df, border="horizontal")

with st.expander("Distinguished Service/Hall of Fame Award Winners"):
    st.table(distinguished_df, border="horizontal")

with st.expander("President's Gavel Award Winners"):
    st.table(gavel_df, border="horizontal")

with st.expander("Innovation Award Winners"):
    st.table(innovation_df, border="horizontal")

with st.expander("Student Award Winners"):
    st.table(student_df, border="horizontal")

with st.expander("Scholarship for Diversity in Librarianship Recipients"):
    st.table(scholarship_df, border="horizontal")
